# Use the official Nginx image as the base image
FROM nginx:latest

# Remove the default Nginx welcome page
RUN rm -rf /usr/share/nginx/html/*

# Copy the contents of the 'html' directory to the Nginx web root
COPY html /usr/share/nginx/html

